from scrapers.static_site.static_store_scraper import StaticStore

from scrapers.static_site.automakers.volvo_pecas import VolvoPecas
from scrapers.static_site.automakers.iveco_mercado_livre import IvecoMercadoLivre
from scrapers.static_site.automakers.volvo_mercado_livre import VolvoMercadoLivre
from scrapers.static_site.automakers.volkswagen_mercado_livre import VolkswagenMercadoLivre

from scrapers.static_site.parallel_market.ja_cotei import JaCotei
from scrapers.static_site.parallel_market.rodoponta import Rodoponta
from scrapers.static_site.parallel_market.zanotto_pecas import ZanottoPecas
from scrapers.static_site.parallel_market.mercado_livre import MercadoLivre
from scrapers.static_site.parallel_market.gigante_autopecas import GiganteAutopecas
from scrapers.static_site.parallel_market.scania_mercado_livre import ScaniaMercadoLivre
from scrapers.static_site.parallel_market.mega_diesel import MegaDiesel
from scrapers.static_site.parallel_market.mundo_caminhao import MundoCaminhao
from scrapers.static_site.parallel_market.loja_dr3 import LojaDr3
from scrapers.static_site.parallel_market.vargas_parts import VargasParts
