from scrapers.dynamic_site.dynamic_store_scraper import DynamicStore

from scrapers.dynamic_site.parallel_market.tresp_autopecas import TrespAutopecas
from scrapers.dynamic_site.parallel_market.connect_parts import ConnectParts
from scrapers.dynamic_site.parallel_market.brasparts import Brasparts
from scrapers.dynamic_site.parallel_market.loja_stemac import LojaStemac